### ISSUE TITLE
Did i loose push access? 

### ISSUE THREAD

**Issue by Hampusm** [KartSriv/Story#15]
I cant write to the readme

**Comment by Hampusm** [comment]
@KartSriv

**Comment by KartSriv** [comment]
Let me check

**Comment by KartSriv** [comment]
**You're still a collaborator.** Send some screenshots.

![image](https://user-images.githubusercontent.com/25691607/55787749-9623b580-5ad4-11e9-9a46-a5bad248cd61.png)

**Comment by Hampusm** [comment]
I get Review required
At least 1 approving review is required by reviewers with write access.

**Comment by KartSriv** [comment]
Try Now
![image](https://user-images.githubusercontent.com/25691607/55853891-9a0d1180-5b80-11e9-94c4-e3abc5da05a8.png)

**Comment by KartSriv** [comment]
Push a Test PR and close this issue.

**Comment by Hampusm** [comment]
@KartSriv can you please disable ”require pull request reviews before merging”. Its just a pain in the butt

**Comment by KartSriv** [comment]
**Done**
![image](https://user-images.githubusercontent.com/25691607/55872795-832fe480-5bab-11e9-8e3d-14a7c72db61b.png)

**Comment by Hampusm** [comment]
@KartSriv thanks
