### ISSUE TITLE
Displaying Story in README

### ISSUE THREAD

**Issue by KartSriv** [KartSriv/Story#7]
@Hampusm I think we should display the story in the README.md because people won't know the story until they go inside the Story folder. I have a open minded so try to convince me on why not to display the story in README. Thanks - Karthik Srivijay

**Comment by Hampusm** [comment]
@KartSriv It's because as the story get longer (it eventually will) it will be a mess to have it all in the readme.
and i also think that its benefiting to have chapters for the sake of having it organized.

**Comment by eclipticrick** [comment]
how about chapter 1 (or part of it) in the read me with a button "keep reading" that opens the story folder

**Comment by KartSriv** [comment]
@eclipticric Love the idea!

**Comment by Hampusm** [comment]
@eclipticrick But that means that the readme will have to be updated every time the first chapter gets updated

**Comment by Hampusm** [comment]
and @KartSriv there is a link to the position of the story in the [readme](README.md)

**Comment by eclipticrick** [comment]
@Hampusm we can start writing in the readme untill it get's too large, and then continue in a chapter 1 file

**Comment by Hampusm** [comment]
@KartSriv I still think it would be pretty ugly though with it in the readme. even if its not that long

**Comment by KartSriv** [comment]
@Hampusm I still don't think people will "SEE" the story yet. @eclipticrick Let's make the previous chapters uneditable.

**Comment by KartSriv** [comment]
@Hampusm Maybe let's create an image with nice fonts and make the first chapter more stylish.

**Comment by Hampusm** [comment]
@KartSriv ok we can do it in the readme. It can be a good idea to also temporarily make the first chapter file redirect to the readme

**Comment by Hampusm** [comment]
I'll handle it

**Comment by KartSriv** [comment]
@Hampusm So you agree on Beautified Picture or something else. If it's beautified picture then I'll take the task cause I know how to use Adobe Illustrator.

**Comment by KartSriv** [comment]
@Hampusm Don't close any issues until you complete it. A friendly advice : )

**Comment by Hampusm** [comment]
@KartSriv yeah. we need a better logo. 
And im done so ill close it again

**Comment by KartSriv** [comment]
@Hampusm Create an issue about the logo. Let's brainstorm! Made it in a jiffy so looks crazy. Good job in README!
