### ISSUE TITLE
New logo design

### ISSUE THREAD

**Issue by Hampusm** [KartSriv/Story#9]
@KartSriv

**Comment by KartSriv** [comment]
I'll assign this to myself

**Comment by Hampusm** [comment]
@KartSriv Progress on the logo?

**Comment by eclipticrick** [comment]
We could incorporate flaticon icons in to the logo if we credit the author :P
https://www.flaticon.com/search?word=marsupials
https://www.flaticon.com/search?word=story

**Comment by Hampusm** [comment]
https://www.flaticon.com/free-icon/fairy-tale_1602750#term=story&page=1&position=16 seems good

**Comment by Hampusm** [comment]
Thanks for the good idea, @eclipticrick

**Comment by KartSriv** [comment]
That's a good idea @eclipticrick! Thanks - Karthik Srivijay

**Comment by KartSriv** [comment]
Fixed in ccb2742e89aebf537b8d3bea137a2aed71139fb8 and d263bb1ba572da4e469c5717dd5f0e4eadc7849. If there is any problem then reopen this issue.
